#!/usr/bin/env python
# -*- coding: UTF-8 -*-
###############################################################################
# chirri
#
#   Chirri Backup main program
#
# -----------------------------------------------------------------------------
# Chirri Backup - Cheap and ugly backup tool
#   Copyright (C) 2016 Gerardo Garcia Peña <killabytenow@gmail.com>
#
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License as published by the Free
#   Software Foundation, either version 3 of the License, or (at your option)
#   any later version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
#   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#   FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
#   more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program. If not, see <http://www.gnu.org/licenses/>.
# 
###############################################################################

from chirribackup.Config import CONFIG
from chirribackup.Logger import logger
import chirribackup.ActionsManager
import sys

try:
    chirribackup.ActionsManager.invoke(CONFIG.args)

except ActionInvocationException, ex:
    logger.error(ex.desc())
    sys.exit(1)

except ChirriException, ex:
    logger.critical(str(ex))
    sys.exit(1)

sys.exit(0)
