#!/usr/bin/env python2
# -*- coding: UTF-8 -*-
###############################################################################
# chirri
#
#   Chirri Backup main program
#
# -----------------------------------------------------------------------------
# Chirri Backup - Cheap and ugly backup tool
#   Copyright (C) 2016 Gerardo Garcia Peña <killabytenow@gmail.com>
#
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License as published by the Free
#   Software Foundation, either version 3 of the License, or (at your option)
#   any later version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
#   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#   FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
#   more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program. If not, see <http://www.gnu.org/licenses/>.
# 
###############################################################################
from chirribackup import ActionsManager
from chirribackup.Config import CONFIG
from chirribackup.Logger import logger
import sys
import pprint

from chirribackup.exceptions import ActionInvocationException, ChirriException

try:
    ActionsManager.invoke(CONFIG.args)

except ActionInvocationException, ex:
    logger.error(ex.desc())
    sys.exit(1)

except ChirriException, ex:
    logger.critical(str(ex))
    sys.exit(1)

except Exception, ex:
    logger.error("dir(Exception)           = (%s)" % ", ".join(dir(Exception)))
    logger.error("dir(Exception.__class__) = (%s)" % ", ".join(dir(Exception.__class__)))
    logger.error("ex.__class__             = [%s]" % ex.__class__)
    logger.error("ex.__class__.__name__    = [%s]" % ex.__class__.__name__)
    logger.error(str(ex))
    logger.error(pprint.PrettyPrinter(depth=6))
    sys.exit(1)
sys.exit(0)
